#!/bin/ksh

. /u1/etc/tmon/tmon_title.conf

dir_date=`date '+%Y%m%d'`
ps_cputime_file="/u3/log/mon_log/ps_cputime.log"
ps_cputime_all_file="/u3/log/mon_log/ps_cputime_all.log"
ps_cputime_file_chk="/u3/log/mon_log/chk/$dir_date/ps_cputime.log"
ps_cputime_file_all_chk="/u3/log/mon_log/chk/$dir_date/ps_cputime_all.log"

chk_du="/u1/etc/tmon/mon_log/chk_mail.log"
chk_du_warn="/u1/etc/tmon/mon_log/chk_mail_warn.log"

chk_du_Y=`timeout 10 cat $chk_du | grep "chk_du" | wc -l`
chk_du_warn_Y=`timeout 10 cat $chk_du_warn | grep "chk_du" | wc -l`

echo " 
   <tr>
     "

if [ "$chk_du_Y" -gt "0" ] ; then 
   echo "
        <th colspan=3 style="background-color:red">磁碟空間 error $chk_du_Y </th>
        "
else
   if [ "$chk_du_warn_Y" -gt "0" ] ; then
      echo "
           <th colspan=3 style="background-color:yellow">磁碟空間 warn $chk_du_warn_Y </th>
	   "
   else	   
      echo "
           <th colspan=3 style="background-color:#FFECC9">檢查 磁碟空間 OK </th>
           "
   fi
fi

echo "<th colspan=5 style="background-color:#FFECC9">大約超過 80 % 需注意 ， 100 % 程式會異常 </th>"

echo "
     </tr>
     "
